export type AlternateExecutionPathCategory =
  | "main_entry"
  | "fallback_entry"
  | "manual_injection"
  | "cli_entry"
  | "batch_or_script_entry"
  | "daemon_or_runtime_entry"
  | "popup_or_ui_entry"
  | "config_entry"
  | "test_entry"
  | "generated_artifact_entry";

export interface AlternatePathDetectionInput {
  path: string;
  content?: string;
}

export interface AlternatePathDetectionResult extends Record<string, unknown> {
  path: string;
  categories: AlternateExecutionPathCategory[];
  reviewHint: string;
}

export function detectAlternateExecutionPath(input: AlternatePathDetectionInput): AlternatePathDetectionResult {
  const path = input.path.split("\\").join("/").toLowerCase();
  const content = (input.content ?? "").toLowerCase();
  const categories = new Set<AlternateExecutionPathCategory>();
  const combined = `${path}\n${content}`;

  if (/(^|\/)(index|main|server|app|cli)\.[cm]?[jt]sx?$/.test(path) || /\bmain\(|createServer\(|listen\(/.test(content)) categories.add("main_entry");
  if (/fallback|backup|legacy|compat|safe[-_]?stop|degraded/.test(combined)) categories.add("fallback_entry");
  if (/manual|inject|override|hook|bootstrap/.test(combined)) categories.add("manual_injection");
  if (/(^|\/)(cli|bin)\//.test(path) || /\bcommander\b|process\.argv|yargs|bin\/env/.test(content)) categories.add("cli_entry");
  if (/(\.bat|\.cmd|\.ps1|\.sh|\.mjs)$/.test(path) || /(^|\/)(scripts|batch|jobs)\//.test(path)) categories.add("batch_or_script_entry");
  if (/daemon|worker|scheduler|service|runtime|watcher|setinterval|cron/.test(combined)) categories.add("daemon_or_runtime_entry");
  if (/popup|ui|window|browser|extension|react|vue|svelte|tsx$|jsx$/.test(combined)) categories.add("popup_or_ui_entry");
  if (/(\.env|config|settings|schema|\.ya?ml|\.toml|package\.json|tsconfig)/.test(combined)) categories.add("config_entry");
  if (/(\.test\.|\.spec\.|__tests__|fixture|mock)/.test(combined)) categories.add("test_entry");
  if (/(^|\/)(dist|build|generated|coverage)\//.test(path) || /generated by|do not edit/.test(content)) categories.add("generated_artifact_entry");

  if (categories.size === 0) categories.add("main_entry");
  return {
    path: input.path,
    categories: [...categories],
    reviewHint: reviewHintFor([...categories]),
  };
}

export function detectAlternateExecutionPaths(inputs: AlternatePathDetectionInput[]): AlternatePathDetectionResult[] {
  return inputs.map(detectAlternateExecutionPath);
}

function reviewHintFor(categories: AlternateExecutionPathCategory[]): string {
  if (categories.includes("fallback_entry")) return "Check fallback and degraded execution paths after a split or refactor.";
  if (categories.includes("manual_injection")) return "Check alternate manual injection or bootstrap paths after module changes.";
  if (categories.includes("cli_entry")) return "Check command-line entrypoints and argument paths after API changes.";
  if (categories.includes("daemon_or_runtime_entry")) return "Check long-running runtime paths, workers, and schedulers after behavior changes.";
  if (categories.includes("popup_or_ui_entry")) return "Check UI load and interaction paths after module or asset changes.";
  if (categories.includes("config_entry")) return "Check config schema and default path compatibility after configuration changes.";
  if (categories.includes("test_entry")) return "Check tests, fixtures, and mocks that exercise alternate paths.";
  if (categories.includes("generated_artifact_entry")) return "Check whether generated artifacts need regeneration or should be left untouched.";
  return "Check primary entrypoint assumptions and any adjacent alternate execution paths.";
}
