export function sessionMonitorHtml(): string {
  return `<!doctype html>
<html lang="ja">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Workbridge Session Monitor</title>
<style>
:root{color-scheme:dark;--bg:#0b1016;--panel:#111923;--border:#263546;--soft:#1d2a38;--text:#eef4fa;--muted:#8fa0b2;--blue:#32a8ff;--green:#48d17d;--yellow:#f7b42c;--red:#ff5964;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;background:var(--bg);color:var(--text)}
*{box-sizing:border-box}body{margin:0;min-width:840px;background:radial-gradient(circle at 18% -10%,#12263a 0,transparent 35%),var(--bg)}
.app{min-height:100vh;padding:20px}.header{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:14px}.brand{display:flex;align-items:center;gap:12px}.mark{width:38px;color:var(--blue);font-size:26px;font-weight:900;transform:skew(-8deg)}h1{margin:0;font-size:21px}.subtitle{color:var(--muted);font-size:12px;margin-top:2px}.connection{display:flex;align-items:center;gap:8px;color:var(--muted);font-size:12px}.live-dot{width:8px;height:8px;border-radius:50%;background:var(--green);box-shadow:0 0 10px var(--green)}.live-dot.off{background:var(--red);box-shadow:none}
.board{border:1px solid var(--border);border-radius:13px;overflow:hidden;background:rgba(17,25,35,.96);box-shadow:0 18px 55px rgba(0,0,0,.28)}.columns,.session-row{display:grid;grid-template-columns:190px minmax(460px,1fr) 118px}.columns{min-height:38px;align-items:center;color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.08em;background:#0e151e;border-bottom:1px solid var(--border)}.columns>div{padding:0 16px}.columns>div:last-child{text-align:center}
.session-row{min-height:132px;border-bottom:1px solid var(--soft)}.session-row:last-child{border-bottom:0}.session-info{padding:17px 16px;border-right:1px solid var(--soft);background:linear-gradient(90deg,rgba(50,168,255,.035),transparent)}.session-title{font-size:17px;font-weight:760;display:flex;align-items:baseline;gap:8px}.session-prefix{color:#7890a7;font:10px ui-monospace,Consolas,monospace}.workspace{margin-top:7px;color:#62c8ff;font-weight:650;font-size:13px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.workspace-detail{margin-top:2px;color:#73879b;font:10px/14px ui-monospace,Consolas,monospace;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.session-meta{margin-top:5px;color:var(--muted);font-size:11px}.call-count{display:inline-flex;margin-top:8px;padding:2px 7px;border:1px solid #35475a;border-radius:5px;color:#c6d2de;font-size:10px;background:#101822}
.node-viewport{min-width:0;padding:15px 10px;overflow-x:auto;scrollbar-width:thin;scrollbar-color:#33475d transparent}.node-strip{display:flex;align-items:center;min-width:max-content;min-height:100px;padding:0 4px}.connector{width:30px;height:1px;background:#526579;position:relative;flex:0 0 30px}.connector:after{content:"";position:absolute;right:-1px;top:-3px;border-left:6px solid #718398;border-top:3px solid transparent;border-bottom:3px solid transparent}
.tool-node{width:164px;min-height:88px;flex:0 0 164px;border:1px solid var(--border);border-radius:9px;padding:9px 10px 8px;background:linear-gradient(145deg,#16212d,#101821);position:relative;transition:.16s}.tool-node:hover{transform:translateY(-1px);border-color:#46617c}.tool-node.success{border-color:#39895b}.tool-node.running{border-color:var(--blue);box-shadow:inset 0 0 22px rgba(50,168,255,.06)}.tool-node.waiting{border-color:#b98418;box-shadow:inset 0 0 22px rgba(247,180,44,.05)}.tool-node.error{border-color:var(--red);box-shadow:inset 0 0 22px rgba(255,89,100,.07)}
.node-number{position:absolute;top:7px;left:8px;min-width:24px;padding:1px 5px;border-radius:5px;color:#b8c5d2;border:1px solid #35495e;background:#0f1720;font:700 10px/16px ui-monospace,Consolas,monospace;text-align:center}.node-dot{position:absolute;top:9px;right:9px;width:7px;height:7px;border-radius:50%;background:currentColor;box-shadow:0 0 8px currentColor}.success .node-dot{color:var(--green)}.running .node-dot{color:var(--blue);animation:pulse 1.05s infinite}.waiting .node-dot{color:var(--yellow);animation:pulse 1.5s infinite}.error .node-dot{color:var(--red)}
.node-main{display:grid;grid-template-columns:23px minmax(0,1fr);gap:7px;margin-top:22px}.tool-icon{color:#90b8d6;font:700 15px/19px ui-monospace,Consolas,monospace}.tool-name{font:680 11px/16px ui-monospace,Consolas,monospace;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.tool-target{color:#bdc9d5;font:10px/15px ui-monospace,Consolas,monospace;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;min-height:15px}.duration{margin-top:7px;color:#d8e2ec;font:650 11px/14px ui-monospace,Consolas,monospace;text-align:center}.running .duration{color:#65bdff}.waiting .duration{color:#ffd36b}.error .duration{color:#ff8790}
.session-state{border-left:1px solid var(--soft);display:grid;place-items:center;padding:12px}.state-chip{display:inline-flex;align-items:center;justify-content:center;gap:8px;min-width:90px;padding:9px 11px;border:1px solid currentColor;border-radius:8px;font-size:12px;font-weight:720;background:rgba(255,255,255,.025)}.state-chip:before{content:"";width:8px;height:8px;border-radius:50%;background:currentColor}.state-chip.running{color:var(--blue)}.state-chip.waiting{color:var(--yellow)}.state-chip.idle{color:var(--green)}.state-chip.error{color:var(--red)}.empty{padding:70px 24px;text-align:center;color:var(--muted)}.empty strong{display:block;color:var(--text);font-size:15px;margin-bottom:6px}@keyframes pulse{0%,100%{opacity:.45;transform:scale(.8)}50%{opacity:1;transform:scale(1.22)}}
@media(max-width:1000px){.columns,.session-row{grid-template-columns:160px minmax(430px,1fr) 104px}.session-info{padding-left:12px;padding-right:12px}}
</style>
</head>
<body><div class="app"><header class="header"><div class="brand"><div class="mark">W</div><div><h1>Workbridge Session Monitor</h1><div class="subtitle">1行 = 1 workspace session · 1ノード = 1ツール呼び出し</div></div></div><div class="connection"><span id="live-dot" class="live-dot"></span><span id="connection-label">接続中</span></div></header><section class="board"><div class="columns"><div>Workspace session</div><div>Tool calls / execution order</div><div>State</div></div><div id="sessions"><div class="empty"><strong>ツール実行を待っています</strong>workspaceIdが確定するとここに追加されます。</div></div></section></div>
<script>
const root=document.getElementById('sessions'),dot=document.getElementById('live-dot'),label=document.getElementById('connection-label');
const states={running:'実行中',waiting:'待機中',idle:'アイドル',error:'エラー'};
const icons={open_workspace:'▰',read:'▤',apply_patch:'✎',exec_command:'>_',write_stdin:'↳',run_workspace_action:'▶',download_artifact:'⇩'};
function esc(v){const m={'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'};return String(v==null?'':v).replace(/[&<>"']/g,c=>m[c])}
function clock(v){return new Intl.DateTimeFormat('ja-JP',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(v))}
function elapsed(v){v=Math.max(0,Number(v)||0);if(v<1000)return Math.round(v)+' ms';if(v<10000)return(v/1000).toFixed(1)+' s';return Math.round(v/1000)+' s'}
function renderNode(n){const duration=n.durationMs==null?Date.now()-n.startedAt:n.durationMs;const exit=n.exitCode!=null&&n.exitCode!==0?' · exit '+esc(n.exitCode):'';return '<article class="tool-node '+esc(n.state)+'" title="'+esc(n.tool+(n.target?': '+n.target:''))+'"><span class="node-number">#'+esc(n.number)+'</span><span class="node-dot"></span><div class="node-main"><span class="tool-icon">'+esc(icons[n.tool]||'◆')+'</span><div><div class="tool-name">'+esc(n.tool)+'</div><div class="tool-target">'+(n.target?esc(n.target):'&nbsp;')+'</div></div></div><div class="duration">'+elapsed(duration)+exit+'</div></article>'}
function renderSession(s){const nodes=s.nodes.map((n,i)=>(i?'<span class="connector"></span>':'')+renderNode(n)).join('');const workspace=s.workspaceLabel||'workspace未確定';const detail=s.workspaceDetail||'';const title=s.workspacePath||workspace;const fullId=s.workspaceId||s.sessionIdPrefix;return '<article class="session-row"><div class="session-info"><div class="session-title">Session '+esc(s.displayNumber)+'<span class="session-prefix" title="'+esc(fullId)+'">'+esc(s.sessionIdPrefix)+'</span></div><div class="workspace" title="'+esc(title)+'">'+esc(workspace)+'</div>'+(detail?'<div class="workspace-detail" title="'+esc(title)+'">'+esc(detail)+'</div>':'')+'<div class="session-meta">Started '+clock(s.startedAt)+'</div><span class="call-count">'+esc(s.totalCalls)+' calls</span></div><div class="node-viewport"><div class="node-strip">'+nodes+'</div></div><div class="session-state"><span class="state-chip '+esc(s.state)+'">'+esc(states[s.state]||s.state)+'</span></div></article>'}
function render(data){if(!data.sessions||!data.sessions.length){root.innerHTML='<div class="empty"><strong>ツール実行を待っています</strong>workspaceIdが確定するとここに追加されます。</div>';return}root.innerHTML=data.sessions.map(renderSession).join('');document.querySelectorAll('.node-viewport').forEach(v=>v.scrollLeft=v.scrollWidth)}
async function refresh(){try{const response=await fetch('/monitor/api/snapshot',{cache:'no-store'});if(!response.ok)throw new Error('HTTP '+response.status);render(await response.json());dot.classList.remove('off');label.textContent='接続中 · 0.5秒更新'}catch(error){dot.classList.add('off');label.textContent='接続エラー'}}
refresh();setInterval(refresh,500);
</script></body></html>`;
}
